function lib = functionlibrarylist(mobj)
%
%-------function help------------------------------------------------------
% NAME
%   functionlibrarylist.m
% PURPOSE
%   Lists available functions for use in DataManip
% USAGE
%   lib = functionlibrarylist(mobj)
%INPUT
%   mobj - handle to calling model - use to subselect
%OUTPUT
%   lib - structure with library listings contains:
%       fname - function names
%       fvars - function input variables
%       fdesc - short description of function
%       nfunc - function id number
%
% Author: Ian Townend
% CoastalSEA (c)June 2019
%--------------------------------------------------------------------------
%
fname = {'moving(x,n,''func'')';...                                         %1
         'movingtime(x,t,''tdur'',''tstep'',''func'')';...                  %2
         'downsample(x,t,''period'',''func'')';...                          %3
         'interpwithnoise(x,t,npad,scale,''method'',ispos)';...             %4
         'subsample_ts(x,t,mobj,''method'')';...                            %5
         'conditional_subsample(x,t,thr,mobj,''method'')';...               %6
         'phaseplot(x,y,t)';...                                             %7
         'recursive_plot(x,''varname'',nint)';...                           %8
         'addslrtotides(x,t,delta,exp-rate,pivot-year)';...                 %9
         'tidalrange(x,t,issave,isplot)';...                                %10
         'tidalrange_nltc(x,t,issave,isplot,''titletext'')';...             %11
         'waterlevelfreqplots(x,t)';...                                     %12
         'frequencyanalysis(x,t,''vardesc'')';...                           %13
         'wave_steepness(x,y,z,t)';...                                      %14
         'wave_scatter(dst)';...                                            %15
         'beachtransportratio(x,theta,isvector)';...                        %16
         'littoraldriftstats(x,t,''period'')';...                           %17
         'posneg_dv_stats(x,t,''varlabel'')';...                            %18
         'binned_wave_climate(x,y,z) or (dst)';...                          %19
         'userderivedoutput(t,x,y,z,flag)';...                              %20
         '[z.*repmat(1,1,length(x),length(y))]';...                         %21
         '[z.*repmat(1,length(t)),length(x),length(y))]';...                %22
         '[NaN;diff(x)]';...                                                %23
         '[diff(x);NaN]';...                                                %24
         'diffpadded(var,n,dim,ispad)'};                                    %25
 
fvars = {'Any variable, number of points in sample window, function (optional, default is mean). Use %time to include time dimension in result';...
         'Any variable, Time, duration to average over (y,d,h,m, or s), duration fo time step (y,d,h,m, or s), function (optional, default is mean)';...  
         'Any variable, Time, period (year,month,day,hour,sec), function (eg mean)';...
         'Variable, Time, No of records, Noise scale factor, Interpolation method, +ve flag (true/false)';...
         'Variable, Time, mobj, Interpolation method (optional, default is linear)';...
         'Variable, Time, Threshold, mobj, Interpolation method (optional, default is linear)';...
         'Any variable, Any variable, time (optional)';...
         'Any variable, Name of variable, offset interval';...         
         'WaterLevels, Time, slr in 1900, exponential rate, pivot year';... 
         'WaterLevels, Time, true to return range values, true to plot results';...
         'WaterLevels, Time, true to return fitted values, true to plot results, text to use on plot';...
         'WaterLevels, Time';...
         'Variable, Time, Variable description';...
         'Wave Height, Wave Period, Depth and Time';...
         ' Depth, as X,Y,Z, using dst assignment';...
         'Wave direction (degTN), Beach angle (degTN), vector output - true/false (optional)';...         
         'Littoral drift, Time, period';...
         'Any +/-ve Variable, Time, variable label text (optional)';...
         'Wave Height, Wave Period, Wave Direcion';...
         'Time,X,Y,Z, flag (''integral'' or ''gradient'')';...
         'X and Y are dimension variables and Z is a 2D dstable variable (no rows)';...
         'X and Y are dimension variables, Z is a 2D dstable variable and T is time';...
         'Variable to be differenced';...
         'Variable to be differenced';...
         'Variable to be differenced, nth difference, dimension to use, ispad true to pad end'};        
       
fdesc = {'Stats - Moving average (or similar statistic)';...
         'Stats - Moving average (or similar) of timeseries, over defined duration, advancing at defined interval';...
         'Data - Down-sample some function of a time series over defined interval';... 
         'Data - Infill record by interpolating and adding noise';...
         'Data - Subsample record at time intervals defined by another record';...
         'Data - Subsample record based on threshold defined by another record';...
         'Plot - Phase plot of two variables as numbered or time-stamped sequence';...
         'Plot - A variable against an offset of itself';...        
         'Data - Add sea level rise to a water level time series (uses exp fun)';...
         'Data - Derive tidal range and mean values from water level timeseries';...
         'Stats - Fit tidal range, HW, LW, etc, to trend and cycles';...
         'Plot - Selection of plots for water level frequency and duration';... 
         'Plot - Selection of frequency analysis plots of timeseries data';...
         'Data - Depth dependent wave steepness';...
         'Plot - Wave height-period scatter plots';...
         'Data - Ratio of alongshore to cross-shore transport';...
         'Plot - Annual and monthly mean plots of littoral drift';... 
         'Plot - Rate of change of volume + plot erosion and accretion histograms';...
         'Stats - Compute equal energy flux bins for the wave height-direction scatter';...
         'Data - Compute the volume under surface at each time step';...
         'Data - Sub-sample an array variable';...
         'Data - Sub-sample a time dependent array variable';...
         'Data - Differences assigned to the end of the difference interval';...
         'Data - Differences assigned to the beginning of the difference interval';...
         'Data - Differences of array padded along selected dimension'};

classmeta = metaclass(mobj);
classname = classmeta.Name;

%now define any subselection so that only valid functions are displayed
switch classname
    case 'Asmita'
        idinc = [1:8,21:25];
    case {'CoastalTools','SpitDeltaSEM','WaveRayModel'}
        idinc = [1:19,21:25];
    case {'TableViewer','EstuaryDB'}
        idinc = [1:8,13,21:25];
    case 'ChannelForm'
        idinc = [1,7,8,21:25];
    case 'Diffusion'
        idinc = [1,20:25];   
    otherwise
        idinc = [1,8,21:25];
end

lib.fname = fname(idinc);
lib.fvars = fvars(idinc);
lib.fdesc = fdesc(idinc);
lib.nfunc = (1:size(lib.fname,1))'; 