function lib = functionlibrarylist(mobj)
%
%-------function help------------------------------------------------------
% NAME
%   functionlibrarylist.m
% PURPOSE
%   Lists available functions for use in DataManip
% USAGE
%   lib = functionlibrarylist(mobj)
%INPUT
%   mobj - handle to calling model - use to subselect
%OUTPUT
%   lib - structure with library listings contains:
%       fname - function names
%       fvars - function input variables
%       fdesc - short description of function
%       nfunc - function id number
%
% Author: Ian Townend
% CoastalSEA (c)June 2019
%--------------------------------------------------------------------------
%
fname = {'moving(x,n,''func'')';... 
         'movingtime(x,t,''tdur'',''tstep'',''func'')';...
         'downsample(x,t,''period'',''func'')';...  
         'interpwithnoise(x,t,npad,scale,''method'',ispos)';...
         'subsample_ts(x,t,mobj,''method'')';...
         'conditional_subsample(x,t,thr,mobj,''method'')';...
         'phaseplot(x,y,t)';...
         'recursive_plot(x,''varname'',nint)';...         
         'addslrtotides(x,t,delta,exp-rate,pivot-year)';...
         'tidalrange(x,t,issave,isplot)';...
         'waterlevelfreqplots(x,t)';...
         'frequencyanalysis(x,t,''vardesc'')';...
         'beachtransportratio(x,theta)';...
         'littoraldriftstats(x,t,''period'')';...  
         'posneg_dv_stats(x,t,''varlabel'')';...
         'userderivedoutput(t,x,y,z,flag)';...
         'z.*repmat(1,1,length(x),length(y))';...
         'z.*repmat(1,length(t)),length(x),length(y))';...
         '[Nan;diff(x,n,dim)]';...
         '[diff(x,n,dim);NaN]'};
 
fvars = {'Any variable, number of points in sample window, function (optional, default is mean). Use %time to include time dimension in result';...
         'Any variable, Time, duration to average over (y,d,h,m, or s), duration fo time step (y,d,h,m, or s), function (optional, default is mean)';...  
         'Any variable, Time, period (year,month,day,hour,sec), function (eg mean)';...
         'Variable, Time, No of records, Noise scale factor, Interpolation method, +ve flag (true/false)';...
         'Variable, Time, mobj, Interpolation method (optional, default is linear)';...
         'Variable, Time, Threshold, mobj, Interpolation method (optional, default is linear)';...
         'Any variable, Any variable, time (optional)';...
         'Any variable, Name of variable, offset interval';...         
         'WaterLevels, Time, slr in 1900, exponential rate, pivot year';... 
         'WaterLevels, Time, true to return range values, true to plot results';...
         'WaterLevels, Time';...
         'Variable, Time, Variable description';...
         'Wave direction (degTN), Beach angle (degTN)';...         
         'Littoral drift, Time, period';...
         'Any +/-ve Variable, Time, variable label text (optional)';...
         'Time,X,Y,Z, flag (''integral'' or ''gradient'')';...
         'X and Y are dimension variables and Z is Array variable (no rows)';...
         'X and Y are dimension variables, Z is Array variable and T is time';...
         'Variable to be differenced, nth difference, dimension to use';...
         'Variable to be differenced, nth difference, dimension to use'};        
       
fdesc = {'Moving average (or simialr statistic)';...
         'Moving average (or similar) of timeseries, over defined duration, advancing at defined interval';...
         'Down-sample some function of a time series over defined interval';... 
         'Infill record by interpolating and adding noise';...
         'Subsample record at time intervals defined by another record';...
         'Subsample record based on threshold defined by another record';...
         'Phase plot of two variables as numbered or time-stamped sequence';...
         'Plot of a variable against an offset of itself';...        
         'Add sea level rise to a water level time series (uses exp fun)';...
         'Derive tidal range and mean values from water level timeseries';...
         'Selection of plots for water level frequency and duration';... 
         'Selection of frequency analysis plots of timeseries data';...
         'Ratio of alongshore to cross-shore transport';...
         'Annual and monthly mean plots of littoral drift';... 
         'Rate of change of volume + plot erosion and accretion histograms';...
         'Compute the volume under surface at each time step';...
         'Sub-sample an array variable';...
         'Sub-sample a time dependent array variable';...
         'Differences assigned to the end of the difference interval';...
         'Differences assigned to the beginning of the difference interval'};

classmeta = metaclass(mobj);
classname = classmeta.Name;

%now define any subselection so that only valid functions are displayed
switch classname
    case 'InWave'
        idinc = [1:12,17:20];
    case 'CoastalTools'
        idinc = [1:15,17:20];
    case 'SpitDeltaSEM'
        idinc = [1:15,17:20];
    case 'Diffusion'
        idinc = [1,15:20];
    otherwise
        idinc = [1,17:20];
end

lib.fname = fname(idinc);
lib.fvars = fvars(idinc);
lib.fdesc = fdesc(idinc);
lib.nfunc = (1:size(lib.fname,1))'; 